#!/usr/bin/env python3
"""
Godelion Analysis: Comprehensive Run Report

Generates an HTML report summarizing the full evolutionary run.
"""

import argparse
import json
import os
from datetime import datetime


def generate_html_report(output_dir: str) -> str:
    """Generate an HTML report of the run."""
    metadata_path = os.path.join(output_dir, "dgm_metadata.jsonl")
    if not os.path.exists(metadata_path):
        return "<p>No metadata found.</p>"

    entries = []
    with open(metadata_path) as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))

    run_id = os.path.basename(output_dir)

    # Collect stats
    total_gens = len(entries)
    total_attempts = sum(len(e.get("children", [])) for e in entries)
    total_compiled = sum(len(e.get("children_compiled", [])) for e in entries)
    final_archive = entries[-1].get("archive", []) if entries else []

    # Per-generation table
    gen_rows = []
    for i, e in enumerate(entries):
        gen_rows.append(f"""<tr>
            <td>{e.get("generation", i)}</td>
            <td>{len(e.get("children", []))}</td>
            <td>{len(e.get("children_compiled", []))}</td>
            <td>{len(e.get("archive", []))}</td>
            <td><small>{str(e.get("selfimprove_entries", []))[:80]}...</small></td>
        </tr>""")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Godelion Report — {run_id}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #f8f9fa; color: #333; }}
  h1 {{ color: #2c3e50; border-bottom: 3px solid #e74c3c; padding-bottom: 10px; }}
  h2 {{ color: #34495e; margin-top: 30px; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }}
  .stat-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .stat-card .value {{ font-size: 28px; font-weight: bold; color: #e74c3c; }}
  .stat-card .label {{ font-size: 12px; color: #7f8c8d; text-transform: uppercase; }}
  table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; }}
  th, td {{ padding: 10px 15px; text-align: left; border-bottom: 1px solid #ecf0f1; }}
  th {{ background: #2c3e50; color: white; }}
  tr:hover {{ background: #f5f6fa; }}
  .warning {{ background: #fff3cd; border: 1px solid #ffc107; padding: 15px; border-radius: 8px; margin: 20px 0; }}
  img {{ max-width: 100%; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin: 10px 0; }}
</style>
</head>
<body>
  <h1>🧬 Godelion Evolution Report</h1>
  <p>Run: <code>{run_id}</code> | Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>

  <div class="stats">
    <div class="stat-card"><div class="value">{total_gens}</div><div class="label">Generations</div></div>
    <div class="stat-card"><div class="value">{total_attempts}</div><div class="label">Self-Improve Attempts</div></div>
    <div class="stat-card"><div class="value">{total_compiled}</div><div class="label">Successful (Compiled)</div></div>
    <div class="stat-card"><div class="value">{len(final_archive)}</div><div class="label">Final Archive Size</div></div>
  </div>

  <div class="warning">
    <strong>⚠️ Safety Notice:</strong> This report documents an evolutionary self-improvement run.
    All code changes were generated by AI and validated on benchmarks. Review patches before
    using outside the experiment.
  </div>

  <h2>Performance Chart</h2>
  <img src="analysis_performance.png" alt="Performance Chart" onerror="this.style.display='none'">

  <h2>Lineage Tree</h2>
  <img src="lineage.png" alt="Lineage Tree" onerror="this.style.display='none'">

  <h2>Generation Details</h2>
  <table>
    <tr><th>Generation</th><th>Attempts</th><th>Compiled</th><th>Archive</th><th>Entries</th></tr>
    {"".join(gen_rows)}
  </table>

  <h2>Final Archive</h2>
  <ul>
    {"".join(f"<li><code>{a}</code></li>" for a in final_archive)}
  </ul>

  <p style="margin-top: 40px; color: #95a5a6; font-size: 12px;">
    Generated by Godelion Analysis Tools
  </p>
</body>
</html>"""

    report_path = os.path.join(output_dir, "report.html")
    with open(report_path, "w") as f:
        f.write(html)
    print(f"Saved: {report_path}")
    return report_path


def main():
    parser = argparse.ArgumentParser(description="Godelion Run Report Generator")
    parser.add_argument("--output-dir", "-o", required=True, help="Godelion output directory")
    parser.add_argument("--format", default="html", choices=["html"], help="Report format")
    args = parser.parse_args()

    generate_html_report(args.output_dir)


if __name__ == "__main__":
    main()
